targets:
  $default:
    builders:
      source_gen:combining_builder:
        generate_for:
          - 'lib/**/*_dto.dart'
          - 'lib/**/*_dvo.dart'
          - '**/form_blocs.dart'

      mek_data_class_generator|data_class:
        generate_for:
          - 'lib/**/*_dto.dart'
          - 'lib/**/*_dvo.dart'
          - '**/form_blocs.dart'
        options:
          pageWidth: 100
          comparable: true
          stringify: true
          copyable: false
          changeable: false
          changesVisible: false

      json_serializable:json_serializable:
        generate_for:
          - 'lib/**/*_dto.dart'
          - 'lib/**/*_dvo.dart'
        options:
          explicit_to_json: true