targets:
  $default:
    builders:
      source_gen:combining_builder:
        generate_for:
          - 'lib/**/*_dto.dart'
          - 'lib/**/*_dvo.dart'
          - '**/form_blocs.dart'

      mek_data_class_generator|data_class:
        generate_for:
          - 'lib/**/*_dto.dart'
          - 'lib/**/*_dvo.dart'
          - '**/form_blocs.dart'
        options:
          pageWidth: 100
          comparable: true
          stringify: true
          copyable: false
          changeable: false
          changesVisible: false

      json_serializable_immutable_collections:
        generate_for:
          - 'lib/**/*_dto.dart'
          - 'lib/**/*_dvo.dart'
        # configure your options here, same as json_serializable
        options:
          any_map: true
          checked: false
          constructor: ""
          create_factory: true
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: false
          field_rename: none
          generic_argument_factories: false
          ignore_unannotated: false
          include_if_null: true
      json_serializable:json_serializable:
        generate_for:
          # exclude everything to avoid conflicts, this library uses a custom builder
          include:
          exclude:
            - '**'