name: mek_gasol
description: A new Flutter project.
version: 0.5.0
publish_to: "none"

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

# DATA
  firebase_core: ^1.22.0
  firebase_auth: ^3.9.0
  cloud_firestore: ^3.4.8
  shared_preferences: ^2.0.15

# DOMAIN
  mek_data_class: ^0.1.0
  json_annotation: ^4.6.0

  collection: ^1.16.0
  rxdart: ^0.27.4
  pure_extensions: ^4.2.0
  intl: ^0.17.0
  get_it: ^7.2.0
  logging: ^1.0.2

  bloc: ^8.1.0
  tuple: ^2.0.0
  decimal: ^2.3.0
  version: ^3.0.2

  riverpod: ^2.0.0-dev.9
  rivertion: ^0.1.0-dev.3
  riverbloc: ^2.0.0-dev.2

  # PRESENTATION
  url_launcher: ^6.1.5
  package_info_plus: ^1.4.3+1

  flutter_riverpod: ^2.0.0-dev.9

  table_calendar: ^3.0.7
  date_picker_timeline: ^1.2.3
  calendar_timeline: ^1.0.5

  flutter_form_bloc:
    git:
      url: https://github.com/BreX900/form_bloc.git
      path: packages/flutter_form_bloc
      ref: release

  mek:
    path: ../mek

dev_dependencies:
  flutter_test:
    sdk: flutter

  mek_lints: ^0.3.0

  # To generate .g files:
  # flutter packages pub run build_runner build --delete-conflicting-outputs
  # flutter packages pub run build_runner watch --delete-conflicting-outputs
  build_runner: ^2.2.1
  mek_data_class_generator: ^0.1.4
  json_serializable: ^6.3.2

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
