name: mek_gasol
description: A new Flutter project.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

# DATA
  firebase_core: ^1.24.0
  firebase_auth: ^3.11.2
  cloud_firestore: ^3.5.1
  firebase_storage: ^10.3.11
  shared_preferences: ^2.0.15

# DOMAIN
  mek_data_class: ^0.2.0
  json_annotation: ^4.7.0

  collection: ^1.16.0
  rxdart: ^0.27.5
  pure_extensions: ^4.2.0
  intl: ^0.17.0
  get_it: ^7.2.0
  logging: ^1.1.0

  bloc: ^8.1.0
  tuple: ^2.0.1
  decimal: ^2.3.0
  version: ^3.0.2

  # PRESENTATION
  flutter_riverpod: ^2.0.2

  go_router: ^5.0.5
  url_launcher: ^6.1.6
  package_info_plus: ^1.4.3+1

  mek:
    path: ../mek

dev_dependencies:
  flutter_test:
    sdk: flutter

  mek_lints: ^0.3.0

  # To generate .g files:
  # flutter packages pub run build_runner build --delete-conflicting-outputs
  # flutter packages pub run build_runner watch --delete-conflicting-outputs
  build_runner: ^2.2.1
  mek_data_class_generator: ^0.2.0
  json_serializable: ^6.5.0
  go_router_builder: ^1.0.14

# TOOLS
  # Dart to typescript
  analyzer: ^5.1.0
  path: ^1.8.2
  glob: ^2.1.0

flutter:
  uses-material-design: true
#  assets:
#    # mek_assets GENERATED CODE - DO NOT MODIFY BY HAND
#    - assets/ravioli/ravioli_carne.png
#    - assets/ravioli/ravioli_gamberi.png
#    - assets/ravioli/ravioli_verdure.png
#    - assets/ravioli/ravioli_xiao_long_bao.png
#    - assets/first_courses/spaghetti_uovo.png
#    - assets/first_courses/riso_gamberetti.png
#    - assets/first_courses/riso_cantonese.png
#    - assets/first_courses/gnocchi_riso.png
#    - assets/first_courses/spaghetti_udon.png
#    - assets/first_courses/riso_verdure_miste.png
#    # mek_assets

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

# https://pub.dev/packages/mek_assets -> dart pub global run mek_assets build
mek_assets:
  format: single
  groups:
    - input_dir: assets
      output_dir: lib/shared/data
      class_name: R
      output_file_name: r