// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaNSS-c-Txqi7xwinn5gvf4Aqktj30ZKE',
    appId: '1:578583198489:web:69ad269ccbcb4378112388',
    messagingSenderId: '578583198489',
    projectId: 'mek-gasol',
    authDomain: 'mek-gasol.firebaseapp.com',
    storageBucket: 'mek-gasol.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC1FnDJ3c5Jo2jqAOFmZdy2vBHXs1tP1o',
    appId: '1:578583198489:android:11aee0ca123a5d58112388',
    messagingSenderId: '578583198489',
    projectId: 'mek-gasol',
    storageBucket: 'mek-gasol.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFZwJGPSexxv1vaZRWNlfR8k1MgEoxW-A',
    appId: '1:578583198489:ios:65cc60f332b2495e112388',
    messagingSenderId: '578583198489',
    projectId: 'mek-gasol',
    storageBucket: 'mek-gasol.appspot.com',
    iosClientId: '578583198489-4mpldnqbk0mjbq9fvkc3petogifq414d.apps.googleusercontent.com',
    iosBundleId: 'mek.gasol.mekGasol',
  );
}
